# Generated by Django 5.2.3 on 2025-06-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronegocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('tipo', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=32, unique=True)),
                ('telefone', models.CharField(max_length=32, unique=True)),
                ('endereco', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='cep',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=32)),
                ('telefone', models.CharField(max_length=32)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agronegocio.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=32)),
                ('unidade', models.CharField(max_length=32)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agronegocio.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('tipo', models.CharField(max_length=32)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agronegocio.cultura')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agronegocio.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPlantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agronegocio.insumo')),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agronegocio.plantio')),
            ],
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_kg', models.FloatField()),
                ('data_colheita', models.DateField()),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agronegocio.plantio')),
            ],
        ),
    ]
