# Generated by Django 5.2.3 on 2025-06-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agronegocio', '0002_cultura_fornecedor_alter_propriedade_cep_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
    ]
